#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

cat <<EOF
  _   _   _   _   _   _   _   _   _   _  
 / \ / \ / \ / \ / \ / \ / \ / \ / \ / \ 
( p | r | e | - | c | o | m | m | i | t )
 \_/ \_/ \_/ \_/ \_/ \_/ \_/ \_/ \_/ \_/
EOF

echo "Running pre-commit checks..."
commit_message="$(cat "$0")"

echo $commit_message
# node ./scripts/pre-commit.js $1