#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "🔍 Running tests before push..."
pnpm run test

if [ $? -ne 0 ]; then
  echo "❌ Tests failed. Push aborted."
  exit 1
fi

echo "✅ Tests passed. Proceeding with push."
