#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

cat <<EOF
  _   _   _   _   _   _   _   _   _   _  
 / \ / \ / \ / \ / \ / \ / \ / \ / \ / \ 
( p | r | e | - | c | o | m | m | i | t )
 \_/ \_/ \_/ \_/ \_/ \_/ \_/ \_/ \_/ \_/
EOF

echo "husky prepare commit message, inputs $0 $1 $2 $3"


# node ./scripts/pre-commit.js $1