name: Pre-release

on:
  push:
    branches:
      - release


jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run:
          echo "There is nothing atm"
  
  Publish:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - run:
          echo "There is nothing atm"